import 'dart:io';
import 'package:path_provider/path_provider.dart';
import 'package:pdf/pdf.dart';
import 'package:pdf/widgets.dart' as pw;

class PdfService {
  // Generate batch report PDF
  Future<File> generateBatchReport({
    required String batchName,
    required DateTime startDate,
    required DateTime? endDate,
    required double initialMoisture,
    required double finalMoisture,
    required String initialMoistureStatus,
    required String finalMoistureStatus,
    required String qualityResult,
    required double confidence,
    required List<Map<String, dynamic>> alerts,
  }) async {
    final pdf = pw.Document();

    final duration = endDate?.difference(startDate) ?? DateTime.now().difference(startDate);
    pdf.addPage(
      pw.Page(
        pageFormat: PdfPageFormat.a4,
        build: (pw.Context context) {
          return pw.Column(
            crossAxisAlignment: pw.CrossAxisAlignment.start,
            children: [
              pw.Text(
                'COPRA DRYING BATCH REPORT',
                style: pw.TextStyle(fontSize: 24, fontWeight: pw.FontWeight.bold),
              ),
              pw.SizedBox(height: 20),
              pw.Text('Batch: $batchName', style: const pw.TextStyle(fontSize: 14)),
              pw.Text('Generated: ${DateTime.now().toString()}', style: const pw.TextStyle(fontSize: 12)),
              pw.SizedBox(height: 20),
              pw.Divider(),
              pw.SizedBox(height: 10),
              pw.Text('BATCH DETAILS', style: pw.TextStyle(fontSize: 14, fontWeight: pw.FontWeight.bold)),
              pw.SizedBox(height: 10),
              pw.Row(
                mainAxisAlignment: pw.MainAxisAlignment.spaceBetween,
                children: [
                  pw.Text('Start Date: ${startDate.toString().split('.')[0]}'),
                  pw.Text('End Date: ${endDate?.toString().split('.')[0] ?? 'Ongoing'}'),
                ],
              ),
              pw.SizedBox(height: 8),
              pw.Row(
                mainAxisAlignment: pw.MainAxisAlignment.spaceBetween,
                children: [
                  pw.Text('Duration: ${duration.inHours}h ${duration.inMinutes % 60}m'),
                  pw.Text('Initial Condition: $initialMoistureStatus'),
                ],
              ),
              pw.SizedBox(height: 8),
              pw.Row(
                mainAxisAlignment: pw.MainAxisAlignment.spaceBetween,
                children: [
                  pw.Text('Final Condition: $finalMoistureStatus'),
                ],
              ),
              pw.SizedBox(height: 20),
              pw.Divider(),
              pw.SizedBox(height: 10),
              pw.Text('QUALITY ASSESSMENT', style: pw.TextStyle(fontSize: 14, fontWeight: pw.FontWeight.bold)),
              pw.SizedBox(height: 10),
              pw.Row(
                mainAxisAlignment: pw.MainAxisAlignment.spaceBetween,
                children: [
                  pw.Text('Result: $qualityResult'),
                  pw.Text('Confidence: ${(confidence * 100).toStringAsFixed(1)}%'),
                ],
              ),
              pw.SizedBox(height: 20),
              if (alerts.isNotEmpty) ...[
                pw.Divider(),
                pw.SizedBox(height: 10),
                pw.Text('ALERTS (${alerts.length})', style: pw.TextStyle(fontSize: 14, fontWeight: pw.FontWeight.bold)),
                pw.SizedBox(height: 10),
                ...alerts.map((alert) => pw.Padding(
                  padding: const pw.EdgeInsets.only(bottom: 5),
                  child: pw.Text(
                    '• ${alert['alertType']}: ${alert['value'].toStringAsFixed(2)} (Threshold: ${alert['threshold'].toStringAsFixed(2)})',
                    style: const pw.TextStyle(fontSize: 10),
                  ),
                )).toList(),
              ],
              pw.SizedBox(height: 30),
              pw.Divider(),
              pw.SizedBox(height: 10),
              pw.Text('Report Generated by CopraWatch', style: const pw.TextStyle(fontSize: 10)),
              pw.Text('© 2026 CopraWatch System', style: const pw.TextStyle(fontSize: 10)),
            ],
          );
        },
      ),
    );

    // Prefer a user-visible folder so exported reports are easy to find.
    final dir = await getDownloadsDirectory() ??
      await getApplicationDocumentsDirectory();
    final fileName = 'CopraWatch_${batchName}_${DateTime.now().millisecondsSinceEpoch}.pdf';
    final file = File('${dir.path}/$fileName');

    await file.writeAsBytes(await pdf.save());
    return file;
  }

  // Generate summary report for multiple batches
  Future<File> generateSummaryReport({
    required List<Map<String, dynamic>> batches,
  }) async {
    final pdf = pw.Document();

    pdf.addPage(
      pw.Page(
        pageFormat: PdfPageFormat.a4,
        build: (pw.Context context) {
          return pw.Column(
            crossAxisAlignment: pw.CrossAxisAlignment.start,
            children: [
              pw.Text(
                'COPRA DRYING SUMMARY REPORT',
                style: pw.TextStyle(fontSize: 24, fontWeight: pw.FontWeight.bold),
              ),
              pw.SizedBox(height: 10),
              pw.Text('Generated: ${DateTime.now().toString()}', style: const pw.TextStyle(fontSize: 12)),
              pw.SizedBox(height: 20),
              pw.Divider(),
              pw.SizedBox(height: 10),
              pw.Text('BATCH SUMMARY (${batches.length} batches)', style: pw.TextStyle(fontSize: 14, fontWeight: pw.FontWeight.bold)),
              pw.SizedBox(height: 10),
              ...batches.map((batch) => pw.Padding(
                padding: const pw.EdgeInsets.only(bottom: 8),
                child: pw.Row(
                  mainAxisAlignment: pw.MainAxisAlignment.spaceBetween,
                  children: [
                    pw.Text(batch['name'] ?? 'Unknown', style: const pw.TextStyle(fontSize: 11)),
                    pw.Text(batch['status'] ?? 'N/A', style: const pw.TextStyle(fontSize: 11)),
                    pw.Text('${(batch['confidence'] ?? 0).toStringAsFixed(0)}%', style: const pw.TextStyle(fontSize: 11)),
                  ],
                ),
              )).toList(),
            ],
          );
        },
      ),
    );

    final dir = await getApplicationDocumentsDirectory();
    final fileName = 'CopraWatch_Summary_${DateTime.now().millisecondsSinceEpoch}.pdf';
    final file = File('${dir.path}/$fileName');

    await file.writeAsBytes(await pdf.save());
    return file;
  }
}
